### ISSUE TITLE
disabling trace output

### ISSUE THREAD

**Issue by mmerickel** [fschwiet/ManyConsole#13]
Is there a reason that the tracing output of a command cannot be disabled? It's currently a private property instead of public/protected?

Anyway I short-circuited the execution to prevent the logging using:

```csharp
public override int? OverrideAfterHandlingArgumentsBeforeRun(string[] remainingArguments)
{
    return this.Run(remainingArguments);
}
```

**Comment by theiviaxx** [comment]
This worked for me, thank you!

**Comment by fschwiet** [comment]
alright maybe I should close this one.
