### ISSUE TITLE
Unexpected (for me!) behavior with just one ConsoleCommand defined

### ISSUE THREAD

**Issue by wexman** [fschwiet/ManyConsole#18]
Hi Frank,

first of all, thanks for providing ManyConsole. I've just begun using it and already like it very much.

I have however run into a problem if there's just one ConsoleCommand defined. This one gets executed even if that command wasn't on the command line, which doesn't seem right for me, or a least we should be able to choose if that's the way we want it. Maybe we can have a "IsDefault" property or something.
For now, I'm working around the issue by having another "dummy" command, but I don't think we should need to have something like that.
Or maybe there's already a way that I just don't see?

Thanks!
Jens

**Comment by fschwiet** [comment]
closing as its stale and afaik working as intended
