### ISSUE TITLE
Handling Arguments to commands

### ISSUE THREAD

**Issue by drusellers** [fschwiet/ManyConsole#21]
How can I specify something like

`git config key value`

Example

`vendor save bill` instead of `vendor save --vendor bill`

I know how to do the latter but not the former.

**Comment by fschwiet** [comment]
Like this, have fun:

	public class Example : ConsoleCommand
	{
		public string Key;
		public string Value;

		public Example()
		{
			this.IsCommand ("config", "Sets a config value.");
			this.HasAdditionalArguments (2, " <key> <value>");
		}

		public override int? OverrideAfterHandlingArgumentsBeforeRun (string[] remainingArguments)
		{
			Key = remainingArguments [0];
			Value = remainingArguments [1];

			return base.OverrideAfterHandlingArgumentsBeforeRun (remainingArguments);
		} 

		public override int Run (string[] remainingArguments)
		{
			Console.WriteLine ("{0} {1}", Key, Value);

			return 0;
		}
	}

**Comment by drusellers** [comment]
AWWWW YEAH

**Comment by drusellers** [comment]
https://github.com/fschwiet/ManyConsole/wiki/Examples
