### ISSUE TITLE
Mutually exclusive parameters

### ISSUE THREAD

**Issue by christianjunk** [fschwiet/ManyConsole#23]
Hi,

is it possible to define mutually exclusive options like the `MutuallyExclusiveSet` in http://commandline.codeplex.com/)?

I want to define two options for a command which are mutually exclusive.

Much thanks and kind regards,

Christian

**Comment by fschwiet** [comment]
No, not directly.  You can add parameter validation to the begging of your Run() override or add an OverrideAfterHandlingArgumentsBeforeRun() override.  The parameter validation can throw a ConsoleHelpAsException exception to present the exception message to the user.
