### ISSUE TITLE
The consoleOut TextWriter is not provided to the commands

### ISSUE THREAD

**Issue by chrischu** [fschwiet/ManyConsole#27]
Hi!

I think it's cool that ManyConsole out of the box needs users to specify the outstream for the console, however it would be even cooler if that TextWriter was also available to commands.

For example when I do further validating of arguments in my command and then want to output an error message I'll have to rely on Console.WriteLine instead of using the passed in TextWriter.

**Comment by fschwiet** [comment]
The textwriter is passed in for testing purposes, so tests can validate what gets written out by ManyConsole.  Whats your goal for having the TextWriter passed through?

If you want to output an error message, consider throwing ConsoleHelpAsException.

**Comment by chrischu** [comment]
Yeah, testing is my exact purpose as well :). 

But you're right it's probably better to just throw ConsoleHelpAsException!

**Comment by fschwiet** [comment]
ok it sounds like you're making progress.  I am going to close this out, and I am not sure about it.  Whoever is passing the textwriter into ManyConsole is passing in the commands to run, so they could inject an alternative if they need it.  Let me know if anything comes up.

**Comment by mwpowellhtx** [comment]
In production, or in test, could be along the lines of [Console.Out](http://msdn.microsoft.com/en-us/library/system.console.out.aspx). Conversely, [Console.In](http://msdn.microsoft.com/en-us/library/system.console.in.aspx). When testing, I like to use a [StringReader](https://msdn.microsoft.com/en-us/library/system.io.stringreader.aspx) to mimic input, for example.
