### ISSUE TITLE
REPL mode?

### ISSUE THREAD

**Issue by stevendesu** [fschwiet/ManyConsole#33]
I'm creating a REPL (Read-Eval-Print Loop) and using ManyConsole to handle the commands for me. For the most part this works beautifully:

```
public static void Main(string[] args)
{
    var commands = GetCommands();
    while (true)
    {
        Console.Write(">");
        var currentCommand = Console.ReadLine();
        
        try
        {
            var returnValue = ConsoleCommandDispatcher.DispatchCommand(commands, currentCommand.Split(' '), Console.Out);
        }
        catch(Exception ex)
        {
            Console.WriteLine("Command threw exception:");
            Console.WriteLine(ex.Message);
        }
}
```

Now I can interact with it as you'd expect:

```
>help

Available commands are:

    Exit        - Exit REPL
    Test        - Test Command

    help <name> - For help with one of the above commands

>Test

Hello, World!
>Exit
```

The problem is when I use `help <name>` it gives me the following:

```
>help Test

'Test' - Test Command

Expected usage: REPL.TestProject.vshost.exe Test

>
```

It assumes the currently running program must prefix all commands, which is not the case. I need either some way to edit the expected usage output, or put ManyConsole into a "REPL mode" where it excludes this.

On a side-note, if there were a "REPL mode" it might be able to replace my entire `Main` function. I could imagine an API like:

```
public static int Main(string[] args)
{
    var commands = GetCommands();
    
    return ConsoleCommandDispatcher.REPL(commands, ">", Console.Out);
}
```

Although if the second parameter were the command line prefix it might make sense to pass in a lambda expression or a function so that it can be variable (if you wanted to print the current working directory or the current database connection or something)

Then again, that might be too much effort and it may just be easier to add a boolean for tweaking the expected output 😄

**Comment by fschwiet** [comment]
There is an existing REPL mode implementation available that solves the first problem, see how ConsoleModeCommand is used in the sample project: https://github.com/fschwiet/ManyConsole/blob/master/SampleConsole/SimpleConsoleModeCommand.cs, I think this will do what you want.  Its not as clean as what you suggest with ConsoleCommandDispatcher.REPL but it should work for you.

**Comment by fschwiet** [comment]
Let me know if you have any problems.
