### ISSUE TITLE
Support attributes

### ISSUE THREAD

**Issue by fleed** [fschwiet/ManyConsole#35]
I'd like support for attributes as alternative to initialisation in constructor:

```csharp
[Command("upload")]
class UploadCommand : ConsoleCommand
{
    [RequiredOption("f|file=")]
    public string Filename { get; set; }
}
```

**Comment by fschwiet** [comment]
There's quite a few other console type utilities that use an attribute based approach, I'm sure you can find one.  There are a number of things I'd do differently but personally I'm not a big fan of using attributes here.
