### ISSUE TITLE
Minor suggestion: Make an overload of ConsoleCommandDispatcher.DispatchCommand that accept a ReadOnlyCollection<string> on the arguments param

### ISSUE THREAD

**Issue by KirillBorunov** [fschwiet/ManyConsole#38]
Use case:
An GUI app written on Visual Basic language with the application framework enabled.
The argument of the Application Startup event returns the command line arguments on a `ReadOnlyCollection<string>` (see https://msdn.microsoft.com/en-us/library/microsoft.visualbasic.applicationservices.windowsformsapplicationbase.startup(v=vs.110).aspx)
The `My.Application.CommandLineArgs` is also return a `ReadOnlyCollection<string>` (see https://msdn.microsoft.com/en-us/library/z2d603cy(v=vs.90).aspx)
There is no direct way to convert that collection to an array. Need to iterate it and copy or use Linq `ToArray()` extension method (the same thing).
But the array can be converted to `ReadOnlyCollection<T>` just calling the `.AsReadOnly()` and is a O(1) operation (see https://msdn.microsoft.com/en-us/library/53kysx7b(v=vs.110).aspx).
Internally you can talk to an `IList<string>` which can hold an `string[]` or an `ReadOnlyCollection<string>` And everybody happy :)

**Comment by fschwiet** [comment]
ToArray() sounds fine, it doesn't sound prohibitively expensive.
