### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by tobimax** [fschwiet/ManyConsole#39]
Hi,

Can you advise of how I could write some tests for my command line. I can't seem to access the command line values as they are part of the dispatch command.

I can test my app / class logic but cannot access the command line values that are parsed.

Thanks

Toby

**Comment by mwpowellhtx** [comment]
IMO, review [this](http://github.com/fschwiet/ManyConsole/blob/master/ManyConsole.Tests/Can_overwrite_options_property.cs) as a start. Put this within your unit test assembly as a kind of Fixture that can verify against some assertions. When you believe the field/property should have been set, then verify some other state, the value itself, or some flag that you set when the property was set. Good luck!

**Comment by fschwiet** [comment]
Closing this issue as its stale.  Please re-open if help is still wanted.
