### ISSUE TITLE
No longer .NET 4.5 compatible but not indicated in nuspec

### ISSUE THREAD

**Issue by pinkfloydx33** [fschwiet/ManyConsole#41]
If the purpose was to break the package so that it is no longer .NET45 compatible, I would suggest updating the nuspec/release notes to include this information.

The current release notes "updated to .NET 4.6.1 or 4.5 or something" make it seem as if both frameworks are included in the package, when only net461 is. You can denote this in the nuspec with target frameworks. 

I  was looking forward to the updates, but can't use anything over 4.5 in my application. Nuget allowed me to install the package and then when I built it I got Framework mismatch errors. Not a big deal, I can continue to use the old version.

Based on the commit history and the latest main branch merge, there is nothing actually .NET 46 dependent that was added into this library. A possible solution would also be adding a NET45-specific csproj/sln (like other libraries do) and including both assemblies (targeting different versions) in the package (under \lib\net45, \lib\net461, etc)

**Comment by pinkfloydx33** [comment]
Another solution would be to put the DLL into \lib\net461 instead of \lib\  Then at least nuget will detect the framework. Otherwise its detected as "valid for all frameworks".

**Comment by fschwiet** [comment]
sorry, you are correct I need to revisit this.

**Comment by fschwiet** [comment]
The .DLL now targets .NET v4.0 again (v1.0.0.2).  Its targeting the client profile, not sure if it was before or not.  Please close out the issue once you've had a chance to verify its ok, or let me know if not.
