### ISSUE TITLE
ManyConsole depends on NDesk.Options 0.2.0

### ISSUE THREAD

**Issue by SorenBech** [fschwiet/ManyConsole#43]
But there is no such version of NDesk.Options.
Please correct the dependency to 0.2.1 to avoid warnings

**Comment by fschwiet** [comment]
Hmm, they must have pulled it from nuget.  I should switch to https://www.nuget.org/packages/Mono.Options/ anyhow, thanks for letting me know this broke.

**Comment by fschwiet** [comment]
updated, thanks
