### ISSUE TITLE
Possibility to omit "Executing command" text

### ISSUE THREAD

**Issue by mduszenko** [fschwiet/ManyConsole#58]
I cannot seem to find a way to omit the "Executing <command> ..." text that is displayed before running any command. The only workaround I was able to think of is to provide `TextWriter.Null` to the `DispatchCommand` function, but this is not really useful, as we lose the help text and error messages as well.

Would you accept a pull request for this feature?

**Comment by fschwiet** [comment]
Does calling SkipsCommandSummaryBeforeRunning() in your command definition do what you want? I suppose it can be called from a parameter handler as well if you want it to be optional. It should skip all output besides what your command writes.

**Comment by mduszenko** [comment]
Yes, this is exactly what I need. I must have missed it. Thank you.
